//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 02:23:00 下午 CST 
//

package com.iisigroup.config.model.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.iisigroup.config.model.jaxb package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Config_QNAME = new QName(
            "http://xmlns.oracle.com/communications/inventory/webservice/IISI/items", "config");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: com.iisigroup.config.model.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ItemList }
     * 
     */
    public ItemList createItemList() {
        return new ItemList();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItemType }
     * {@code >}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/communications/inventory/webservice/IISI/items", name = "config")
    public JAXBElement<ItemType> createConfig(ItemType value) {
        JAXBElement<ItemType> result = new JAXBElement<ItemType>(_Config_QNAME, ItemType.class, null, value);

        return result;
    }

}
