//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.25 at 02:23:00 下午 CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xmlns.oracle.com/communications/inventory/webservice/IISI/items", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.iisigroup.config.model.jaxb;
